version: "3.8"
services:
  keigo_converted_server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: aizu-go-kapro/keigo:latest
    ports:
      - 3000:3000
    restart: always